# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'content.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontent.proto\x12\x07truffle\"0\n\x0b\x43odeContent\x12\x10\n\x08metadata\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1e\n\x0bTextContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\".\n\x0c\x45rrorContent\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\".\n\x0cMediaContent\x12\x10\n\x08metadata\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\xb1\x01\n\x0bRichContent\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.truffle.RichContent.RichContentType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"]\n\x0fRichContentType\x12\x17\n\x13RICHCONTENT_DEFAULT\x10\x00\x12\x18\n\x14RICHCONTENT_MARKDOWN\x10\x01\x12\x17\n\x13RICHCONTENT_UNKNOWN\x10\x02\";\n\x07ToolUse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\x12\x14\n\x0chas_response\x18\x03 \x01(\x08\"\xb8\x03\n\x07\x43ontent\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.truffle.Content.ContentType\x12$\n\x04\x63ode\x18\x02 \x01(\x0b\x32\x14.truffle.CodeContentH\x00\x12#\n\x03rtf\x18\x03 \x01(\x0b\x32\x14.truffle.RichContentH\x00\x12&\n\x05media\x18\x04 \x01(\x0b\x32\x15.truffle.MediaContentH\x00\x12$\n\x04text\x18\x05 \x01(\x0b\x32\x14.truffle.TextContentH\x00\x12&\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x15.truffle.ErrorContentH\x00\x12\'\n\x08tool_use\x18\x07 \x01(\x0b\x32\x10.truffle.ToolUseH\x01\x88\x01\x01\"\x7f\n\x0b\x43ontentType\x12\x13\n\x0f\x43ONTENT_DEFAULT\x10\x00\x12\x10\n\x0c\x43ONTENT_CODE\x10\x01\x12\x11\n\rCONTENT_MEDIA\x10\x02\x12\x10\n\x0c\x43ONTENT_RICH\x10\x03\x12\x11\n\rCONTENT_ERROR\x10\x04\x12\x11\n\rCONTENT_OTHER\x10\x05\x42\t\n\x07\x63ontentB\x0b\n\t_tool_useB\x0fZ\rcore/protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rcore/protobuf'
  _globals['_CODECONTENT']._serialized_start=26
  _globals['_CODECONTENT']._serialized_end=74
  _globals['_TEXTCONTENT']._serialized_start=76
  _globals['_TEXTCONTENT']._serialized_end=106
  _globals['_ERRORCONTENT']._serialized_start=108
  _globals['_ERRORCONTENT']._serialized_end=154
  _globals['_MEDIACONTENT']._serialized_start=156
  _globals['_MEDIACONTENT']._serialized_end=202
  _globals['_RICHCONTENT']._serialized_start=205
  _globals['_RICHCONTENT']._serialized_end=382
  _globals['_RICHCONTENT_RICHCONTENTTYPE']._serialized_start=289
  _globals['_RICHCONTENT_RICHCONTENTTYPE']._serialized_end=382
  _globals['_TOOLUSE']._serialized_start=384
  _globals['_TOOLUSE']._serialized_end=443
  _globals['_CONTENT']._serialized_start=446
  _globals['_CONTENT']._serialized_end=886
  _globals['_CONTENT_CONTENTTYPE']._serialized_start=735
  _globals['_CONTENT_CONTENTTYPE']._serialized_end=862
# @@protoc_insertion_point(module_scope)
