# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: context.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'context.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontext.proto\x12\x03\x61pp\"\xf4\x01\n\x0c\x43ontextEntry\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".app.ContextEntry.ContextEntryType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\x05index\x18\x03 \x01(\rH\x00\x88\x01\x01\"\x82\x01\n\x10\x43ontextEntryType\x12\x11\n\rCTX_UNDEFINED\x10\x00\x12\x15\n\x11\x43TX_USER_RESPONSE\x10\x01\x12\x11\n\rCTX_ASSISTANT\x10\x02\x12\x13\n\x0f\x43TX_TOOL_RESULT\x10\x03\x12\x0e\n\nCTX_SYSTEM\x10\x04\x12\x0c\n\x08\x43TX_FILE\x10\x05\x42\x08\n\x06_index\"\x8b\x01\n\x0bPrevContext\x12*\n\x05state\x18\x01 \x03(\x0b\x32\x1b.app.PrevContext.StateEntry\x12\"\n\x07\x63ontext\x18\x02 \x03(\x0b\x32\x11.app.ContextEntry\x1a,\n\nStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'context_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREVCONTEXT_STATEENTRY']._loaded_options = None
  _globals['_PREVCONTEXT_STATEENTRY']._serialized_options = b'8\001'
  _globals['_CONTEXTENTRY']._serialized_start=23
  _globals['_CONTEXTENTRY']._serialized_end=267
  _globals['_CONTEXTENTRY_CONTEXTENTRYTYPE']._serialized_start=127
  _globals['_CONTEXTENTRY_CONTEXTENTRYTYPE']._serialized_end=257
  _globals['_PREVCONTEXT']._serialized_start=270
  _globals['_PREVCONTEXT']._serialized_end=409
  _globals['_PREVCONTEXT_STATEENTRY']._serialized_start=365
  _globals['_PREVCONTEXT_STATEENTRY']._serialized_end=409
# @@protoc_insertion_point(module_scope)
